name: sproutly
description: Plant Care & Expert Consultation App
version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  google_fonts: ^6.1.0

flutter:
  uses-material-design: true
  assets:
    - assets/images/logo_splash.png
    - assets/images/logo_login.png
    - assets/images/logo_forgot.png
